Grading at 10/24/2024:14:56:02.534834
For commit ID bb29ce2bf30c901ec8db06158065cf037615d6e7
Grading at Thu Oct 24 10:56:00 AM EDT 2024
Doing some basic checking for your submission

Step 1
Checking that story-step1 compiles
rm -f *~ story-step1 story-step2 story-step3 story-step4 story-step1.o story-step2.o story-step3.o story-step4.o rand_story.o
gcc -std=gnu99 -pedantic -Wall -Werror -ggdb3 -c rand_story.c
gcc -std=gnu99 -pedantic -Wall -Werror -ggdb3 -c story-step1.c
gcc -o story-step1 story-step1.o rand_story.o provided.o
rm story-step1.o
The code compiled (good)
Executable story-step1 exists (good)
Checking with provided test case story.txt
Your file matched the expected output
Now running YOUR tests for step 1

1.1: Current test is story-step1 story.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind reported errors or memory leaks:
==1691739== Memcheck, a memory error detector
==1691739== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1691739== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==1691739== Command: ./story-step1 story.txt
==1691739== Parent PID: 1691738
==1691739== 
==1691739== 
==1691739== HEAP SUMMARY:
==1691739==     in use at exit: 12 bytes in 3 blocks
==1691739==   total heap usage: 7 allocs, 4 frees, 8,796 bytes allocated
==1691739== 
==1691739== 12 bytes in 3 blocks are definitely lost in loss record 1 of 1
==1691739==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1691739==    by 0x490B58E: strdup (strdup.c:42)
==1691739==    by 0x1098DC: replace_blanks_with_words (rand_story.c:82)
==1691739==    by 0x109461: main (story-step1.c:16)
==1691739== 
==1691739== LEAK SUMMARY:
==1691739==    definitely lost: 12 bytes in 3 blocks
==1691739==    indirectly lost: 0 bytes in 0 blocks
==1691739==      possibly lost: 0 bytes in 0 blocks
==1691739==    still reachable: 0 bytes in 0 blocks
==1691739==         suppressed: 0 bytes in 0 blocks
==1691739== 
==1691739== For lists of detected and suppressed errors, rerun with: -s
==1691739== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

Step 2
Checking that story-step2 compiles
rm -f *~ story-step1 story-step2 story-step3 story-step4 story-step1.o story-step2.o story-step3.o story-step4.o rand_story.o
gcc -std=gnu99 -pedantic -Wall -Werror -ggdb3 -c rand_story.c
gcc -std=gnu99 -pedantic -Wall -Werror -ggdb3 -c story-step2.c
gcc -o story-step2 story-step2.o rand_story.o provided.o
rm story-step2.o
The code compiled (good)
Executable story-step2 exists (good)
Now running YOUR tests for step 2

2.1: Current test is story-step2 words.txt
-----------------------------
Your output looks good. Lets check valgrind
Valgrind reported errors or memory leaks:
==1691798== Memcheck, a memory error detector
==1691798== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1691798== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==1691798== Command: ./story-step2 words.txt
==1691798== Parent PID: 1691797
==1691798== 
==1691798== 
==1691798== HEAP SUMMARY:
==1691798==     in use at exit: 186 bytes in 13 blocks
==1691798==   total heap usage: 22 allocs, 9 frees, 9,074 bytes allocated
==1691798== 
==1691798== 186 (72 direct, 114 indirect) bytes in 1 blocks are definitely lost in loss record 5 of 5
==1691798==    at 0x484DCD3: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==1691798==    by 0x1095E9: read_categories (rand_story.c:38)
==1691798==    by 0x109466: main (story-step2.c:18)
==1691798== 
==1691798== LEAK SUMMARY:
==1691798==    definitely lost: 72 bytes in 1 blocks
==1691798==    indirectly lost: 114 bytes in 12 blocks
==1691798==      possibly lost: 0 bytes in 0 blocks
==1691798==    still reachable: 0 bytes in 0 blocks
==1691798==         suppressed: 0 bytes in 0 blocks
==1691798== 
==1691798== For lists of detected and suppressed errors, rerun with: -s
==1691798== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

Step 3
Checking that story-step3 compiles
rm -f *~ story-step1 story-step2 story-step3 story-step4 story-step1.o story-step2.o story-step3.o story-step4.o rand_story.o
gcc -std=gnu99 -pedantic -Wall -Werror -ggdb3 -c rand_story.c
gcc -std=gnu99 -pedantic -Wall -Werror -ggdb3 -c story-step3.c
gcc -o story-step3 story-step3.o rand_story.o provided.o
rm story-step3.o
The code compiled (good)
Executable story-step3 exists (good)
Now running YOUR tests for step 3

3.1: Current test is story-step3 words.txt story2.txt
-----------------------------
It looks like you got different output from us on that case.
Here is the diff (yours on left, ours on right):

Once upon a time, there was a walrus. This walrus lived in a 	Once upon a time, there was a walrus. This walrus lived in a 
peculiar cave. One day, it left its peculiar peculiar and met |	peculiar cave. One day, it left its peculiar cave and met a w
Your file did not match the expected output


Step 4
Checking that story-step4 compiles
rm -f *~ story-step1 story-step2 story-step3 story-step4 story-step1.o story-step2.o story-step3.o story-step4.o rand_story.o
gcc -std=gnu99 -pedantic -Wall -Werror -ggdb3 -c rand_story.c
gcc -std=gnu99 -pedantic -Wall -Werror -ggdb3 -c story-step4.c
gcc -o story-step4 story-step4.o rand_story.o provided.o
rm story-step4.o
The code compiled (good)
Executable story-step4 exists (good)
Now running YOUR tests for step 4

4.1: Current test is story-step4 words.txt story2.txt
-----------------------------
It looks like you got different output from us on that case.
Here is the diff (yours on left, ours on right):

Once upon a time, there was a walrus. This walrus lived in a 	Once upon a time, there was a walrus. This walrus lived in a 
peculiar cave. One day, it left its peculiar peculiar and met |	peculiar cave. One day, it left its peculiar cave and met a w
Your file did not match the expected output


4.2: Current test is story-step4 -n words.txt story2.txt
-----------------------------
It looks like you got different output from us on that case.
Here is the diff (yours on left, ours on right):

Once upon a time, there was a walrus. This walrus lived in a 	Once upon a time, there was a walrus. This walrus lived in a 
peculiar cave. One day, it left its peculiar peculiar and met |	peculiar cave. One day, it left its peculiar cave and met a d
Your file did not match the expected output


You have NOT passed your test cases!
You should go and figure out/understand where thing went wrong
And fix the problem(s) before the deadline

Overall Grade: NO GRADE YET
